### ISSUE TITLE
Project license

### ISSUE THREAD

**Issue by gsantner** [regularkid/ohflip#1]
Hello I found that game by looking for some simple small games to quickly open on phone.

I couldn't find any license information in this repository or a file.
What is the license of this project, MIT?
Can you please add a license file?

Thanks :)
@regularkid

**Comment by regularkid** [comment]
Hi Gregor!

Thanks for checking out oh, flip! Hope you had fun playing it!

I usually don't put a license file in my git hub projects - I do them just
for fun :)

What are you looking to do with the game? I'm considering making an iOS /
Android port in the future, though so I'd like to keep the all rights to
the game/code.

- Bryan Perfetto

**Comment by gsantner** [comment]
Yeah is a pretty nice idea for a game jam :D. Actually tried quite some games, and this game is on the list of those which worked fine with touch for me :+1: 

I'm getting a Ubuntu touch phone. And there are barely any games and apps for  it available, so at least can play something in browser, or package for my phone.
so maybe wanna create a desktop launcher/shortcut/starter with icon for ohflip and share with others.
but I don't wanna do this when I don't know what license it is - no license is propriatry and not suitable for that for me :D 
<https://ubports.com/>

In any case, if you want keep all rights, write it down - like all rights reserved and stuff.  stuff on github hasnt to be open source licensed of course, it's fine to have prop on it. to announce somewhere how and what are the license terms for the thing is important, for you and people using it

**Comment by gsantner** [comment]
https://ubports.com/de_DE/

**Comment by regularkid** [comment]
Interesting, I'd never heard of Ubuntu touch phones :) Neat

You should be able to run the game in a browser on your phone. It's hosted
here: www.supermicrofun.com/ohflip

Let me know if that works!

- Bryan Perfetto
